- name: install EPEL repo
  yum: name=epel-release state=present

- name: Install nginx
  yum: name=nginx state=present

- name: Install Git
  yum: name=git state=present

- name: Clone repo
  git:
    repo: https://github.com/alexindris/TestCloud.git
    clone: yes
    update: yes
    dest: ./TestCloud

- name: Copy file to destination
  copy:
    src: ./TestCloud/index.html
    remote_src: true
    dest: /usr/share/nginx/html/index.html

- name: Add firewall exception
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
