- name: Include vars of fileUsers.yml into the 'users' variable
  include_vars:
    file: ../vars/fileUsers.yml

- name: Create users from file
  user:
    name: "{{ item.user }}"
  with_items: "{{ users }}"
