- name: install Epel
  yum:
    name: epel-release
    state: latest

- name: install Nginx
  yum: 
    name: nginx
    state: latest

- name: install Git
  yum:
    name: git
    state: latest

- name: clone repository
  git:
    repo: https://github.com/Josep-Andreu/Optativa-cloud
    clone: yes
    update: yes
    dest: ./lab1 
    version: juan_azogue

- name: copy paste
  copy:
    src: ./lab1/index.html
    remote_src: true
    dest: /usr/share/nginx/html/index.html

- name: restart server
  service:
    name: nginx
    state: restarted
    enabled: yes
