- name: Install EPEL
  yum: name=epel-release state=present

- name: Install apache
  yum: name=httpd state=present

- name: Changing httpd.conf file
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'Require all denied'
    replace: 'Require all granted'