- name: Install EPEL
  yum: name=epel-release state=present

- name: Install nginx
  yum: name=nginx state=present

- name: Install git
  yum: name=git state=present

- name: clone repository
  git: repo=https://github.com/Josep-Andreu/Optativa-cloud dest=./prac1 clone=yes update=yes version=judith_barberan

- name: copy file
  copy: src=./prac1/alumnes/index.html dest=/usr/share/nginx/html/index.html remote_src=yes

- name: restart service
  service: name=nginx state=restarted